export const ICONS: Record<string, any> = {
    remove: 'heroicons_outline:trash',
    'question-sign': 'heroicons_outline:question-mark-circle',
    'new-window': 'mat_solid:copy_all',
    'minus-square-o': 'feather:minus-square',
    cog: 'heroicons_outline:cog-8-tooth',
    move: 'feather:move',
    wrench: 'heroicons_outline:wrench-screwdriver',
    save: 'mat_outline:save',
    copy: 'feather:copy',
    calendar: 'heroicons_outline:calendar-days',
    file: 'mat_outline:attach_file',
    wpforms: 'mat_outline:table_view',
    'files-o': 'mat_outline:content_copy',
    refresh: 'feather:refresh-cw',
    indent: 'heroicons_outline:bars-3-center-left',
    tasks: 'mat_outline:task',
    th: 'heroicons_outline:table-cells',
    'th-list': 'feather:layout',
    'folder-open': 'heroicons_outline:folder-open',
    'folder-o': 'feather:folder',
    'user-secret': 'mat_outline:badge',
    table: 'heroicons_outline:table-cells',
    pencil: 'heroicons_outline:pencil',
    code: 'heroicons_outline:code-bracket',
    terminal: 'feather:terminal',
    home: 'heroicons_outline:home',
    html5: 'heroicons_outline:code-bracket-square',
    list: 'mat_outline:format_list_bulleted',
    usd: 'mat_outline:attach_money',
    hashtag: 'heroicons_outline:hashtag',
    tags: 'heroicons_outline:tag',
    at: 'heroicons_outline:at-symbol',
    font: 'mat_outline:font_download',
    asterisk: 'heroicons_outline:eye-slash',
    plus: 'heroicons_outline:plus',
    'plus-square': 'feather:plus-square',
    'plus-square-o': 'feather:plus-circle',
    'dot-circle-o': 'heroicons_outline:check-circle',
    'phone-square': 'heroicons_outline:phone',
    'clock-o': 'heroicons_outline:clock',
    link: 'heroicons_outline:link',
    columns: 'heroicons_outline:view-columns',
    'th-large': 'mat_outline:category',
    'list-alt': 'heroicons_outline:credit-card',
    'square-o': 'heroicons_outline:bookmark-square',
    cubes: 'heroicons_outline:cube',
    stop: 'heroicons_outline:stop',
    'check-square': 'feather:check-square',
    'remove-circle': 'heroicons_outline:x-circle',
    bars: 'heroicons_outline:bars-4'
};

export default (iconset: string | undefined, name: string, spinning?: boolean) => {
    if (ICONS[name]) {
        name = ICONS[name];
    }
    return `${name}`;
};
