export const ICONS: Record<string, any> = {
    remove: 'formio:trash',
    'question-sign': 'formio:question-mark-circle',
    'new-window': 'formio:copy_all',
    'minus-square-o': 'formio:minus-square',
    cog: 'formio:cog-8-tooth',
    move: 'formio:move',
    wrench: 'formio:wrench-screwdriver',
    save: 'formio:save',
    copy: 'formio:copy',
    calendar: 'formio:calendar-days',
    file: 'formio:attach_file',
    wpforms: 'formio:table_view',
    'files-o': 'formio:content_copy',
    refresh: 'formio:refresh-cw',
    indent: 'formio:bars-3-center-left',
    tasks: 'formio:task',
    th: 'formio:table-cells',
    'th-list': 'formio:layout',
    'folder-open': 'formio:folder-open',
    'folder-o': 'formio:folder',
    'user-secret': 'formio:badge',
    table: 'formio:table-cells',
    pencil: 'formio:pencil',
    code: 'formio:code-bracket',
    terminal: 'formio:terminal',
    home: 'formio:home',
    html5: 'formio:code-bracket-square',
    list: 'formio:format_list_bulleted',
    usd: 'formio:attach_money',
    hashtag: 'formio:hashtag',
    tags: 'formio:tag',
    at: 'formio:at-symbol',
    font: 'formio:font_download',
    asterisk: 'formio:eye-slash',
    plus: 'formio:plus',
    'plus-square': 'formio:plus-square',
    'plus-square-o': 'formio:plus-circle',
    'dot-circle-o': 'formio:check-circle',
    'phone-square': 'formio:phone',
    'clock-o': 'formio:clock',
    link: 'formio:link',
    columns: 'formio:view-columns',
    'th-large': 'formio:category',
    'list-alt': 'formio:credit-card',
    'square-o': 'formio:bookmark-square',
    cubes: 'formio:cube',
    stop: 'formio:stop',
    'check-square': 'formio:check-square',
    'remove-circle': 'formio:x-circle',
    bars: 'formio:bars-4'
};

export default (iconset: string | undefined, name: string, spinning?: boolean) => {
    if (ICONS[name]) {
        name = ICONS[name];
    }
    return `${name}`;
};
